version: '3.9'

services:
  db:
    container_name: gif_api_postgres
    hostname: db
    image: postgres:15.1
    env_file:
      - ./.env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

  backend:
    container_name: gif_api_backend
    hostname: backend
    build:
      context: .
      dockerfile: deploy/Dockerfile
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
      - WAIT_HOSTS=db:${POSTGRES_PORT}
    ports:
      - '8000:8000'
    depends_on:
      - db

  nginx:
    container_name: gif_api_nginx
    hostname: nginx
    image: nginx:1.23
    volumes:
      - ./configuration/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:8080'
    depends_on:
      - backend
