"""empty message

Revision ID: e32cd39d8e56
Revises: 99c36a7f47dc
Create Date: 2022-12-18 22:56:32.190084

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e32cd39d8e56"
down_revision = "99c36a7f47dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trending",
        sa.Column(
            "trending_id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("gif_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "trending_date", sa.Date(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["gif_id"], ["gif.gif_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("trending_id"),
        sa.UniqueConstraint("trending_id"),
    )
    op.create_unique_constraint(None, "gif", ["gif_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "gif", type_="unique")
    op.drop_table("trending")
    # ### end Alembic commands ###
